<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Apply Discount Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?= /* @escapeNotVerified */ $block->getUrl('multiCoupon/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCodeMultiCoupon":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "removeCouponCodeSelector": "#remove_coupon_code",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="coupon_code" class="label"><span><?= /* @escapeNotVerified */ __('Enter discount code') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="" placeholder="<?= $block->escapeHtml(__('Enter discount code')) ?>"/>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action apply primary" type="button" value="<?= /* @escapeNotVerified */ __('Apply Discount') ?>">
                            <span><?= /* @escapeNotVerified */ __('Apply Discount') ?></span>
                        </button>
                    </div>
                </div>
            </div>

            <?php if (strlen($block->getCouponCode())) : ?>
                <div class="coupon-list">
                    <input type="hidden" name="remove_coupon_code" id="remove_coupon_code" value="" />
                    <div class="title" data-role="title">
                        <strong role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Coupons List') ?></strong>
                    </div>
                    <ul>
                        <?php foreach (explode(',', $block->getCouponCode()) as $coupon) : ?>
                            <li>
                                <span class="rm-coupon-cd"><?php echo $block->escapeHtml($coupon) ?></span>
                                <button  type="button" class="action cancel" value="<?= /* @escapeNotVerified */ __('Cancel Coupon') ?>">
                                    <span><?= /* @escapeNotVerified */ __('Cancel Coupon') ?></span>
                                </button>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif ?>
        </form>
    </div>
</div>
